<a href="https://colab.research.google.com/github/Mansihpatel/Data_analysis/blob/master/DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic python

## Arthmetic operations

In [ ]:
2+3+5

10

In [ ]:
100/7

14.285714285714286

In [ ]:
100//7

14

In [ ]:
100%7

2

cost of ice bag ($) = 1.25

profit margin = 20% = .2

profit per bag = profit margin * cost of ice bag
               
No of bags = 500

total profit = no.of bags * profit per bag
             = 500 * (0.2*1.25)


In [ ]:
500*(0.2*1.25)

125.0

In [ ]:
#cost of ice bag ($) = 1.25
cost_of_icebag = 1.25

#profit margin = 20% = .2
profit_margin = 0.2

#profit per bag = profit margin * cost of ice bag
profit_per_bag = cost_of_icebag * profit_margin

#No of bags = 500
no_of_bags = 500

#total profit = no.of bags * profit per bag 
total_profit = no_of_bags * profit_per_bag
total_profit

0.25


125.0

In [ ]:
print("total profit is ",total_profit)

total profit is  125.0


## comparision operator

In [ ]:
my_favourite_number = 1
my_least_favourite_number = 5
a_neutral_number = 3

In [ ]:
# euality check    True
my_favourite_number ==1

True

In [ ]:
# euality check    False
my_favourite_number == my_least_favourite_number


False

In [ ]:
# not equal check - True
my_favourite_number != my_least_favourite_number

True

In [ ]:
# not equal check - False
a_neutral_number != 3

False

In [ ]:
# greater than True
my_least_favourite_number > my_favourite_number >0

True

In [ ]:
# greater than false
my_least_favourite_number>10

False

In [ ]:
# greater or equal True
my_favourite_number >=1 

True

In [ ]:
# greater or equal False
my_favourite_number >= 3

False

In [ ]:
# less than equal to True
3*3 <= 10


True

##Combining conditions with logical operators


In [ ]:
my_favourite_number

1

In [ ]:
my_favourite_number >0 and  my_favourite_number <4

True

In [ ]:
my_favourite_number >0 and my_least_favourite_number >6

False

In [ ]:
my_favourite_number >0 or my_least_favourite_number >6

True

In [ ]:
True and False

False

In [ ]:
False and True

False

In [ ]:
True and True

True

In [ ]:
False and False

False

##The not operator returns False if a condition is True and True if the condition is False.



In [ ]:
not my_favourite_number == 1

False

## Logical operators can be combined to form complex conditions. Use round brackets or parentheses ( and ) to indicate the order in which logical operators should be applied.

In [ ]:
(2 > 3 and 4 <= 5) or not (my_favourite_number < 0 and True)


True

In [ ]:
not True and 0 < 1 or False and True


False

# variables and data types

In [ ]:
my_favorite_color = "blue"

In [ ]:
my_favorite_color

'blue'

In [ ]:
color1 = color2 = "red","green"

In [ ]:
color2

('red', 'green')

In [ ]:
color3 = color4 = "magenta"

In [ ]:
counter = 10
counter = counter+1

In [ ]:
counter

11

In [ ]:
counter += 4

In [ ]:
counter

15

In [ ]:
counter *= 4
counter

60

## variable naming 

In [ ]:
a_variable = 23
is_today_Saturday = False
my_favorite_car = "Delorean"
the_3_musketeers = ["Athos", "Porthos", "Aramis"] 

## Built-in data types in Python

type()  to check data type

In [ ]:
a_variable

23

In [ ]:
type(a_variable)

int

In [ ]:
type(is_today_Saturday)

bool

In [ ]:
type(my_favorite_car)


str

In [ ]:
type(the_3_musketeers)

list

## Python has several built-in data types for storing different kinds of information in variables. Following are some commonly used data types:

**Integer**
**Float**
**Boolean**
**None**
**String**
**List**
**Tuple**
**Dictionary**.

Integer, float, boolean, None, and string are **primitive** data types because they represent a single value. Other data types like list, tuple, and dictionary are often called **data** **structures** or containers because they hold multiple pieces of data together.

### Integer


In [ ]:
current_year = 2020


In [ ]:
type(current_year)

int

In [ ]:
a_large_negative_number = -23374038374832934334234317348343

In [ ]:
type(a_large_negative_number)

int

### float

In [ ]:
pi = 3.14
type(pi)

float

In [ ]:
num = 3.0
type(num)

float

In [ ]:
num2 = 4.0
type(num2)

float

In [ ]:
# Floating point numbers can also be written using the scientific notation with an "e" to indicate the power of 10.

small_num = 1e-4
small_num

0.0001

In [ ]:
# avagadro number 
avogadro_num = 6.2345e+23
avogadro_num
type(avogadro_num)

float

In [ ]:
# convert int -> float and float -> int
float(current_year)


2020.0

In [ ]:
int(avogadro_num)

623450000000000047710208

In [ ]:
type(10*3)

int

In [ ]:
type(10.0 *3.0)

float

In [ ]:
type(10/2)

float

In [ ]:
type(10//2)

int

###Boolean


In [ ]:
#Booleans represent one of 2 values: True and False. Booleans have the type bool.

#Booleans are generally the result of a comparison operation, e.g., ==, >=, etc.




In [ ]:
is_today_Sunday = True


In [ ]:
type(is_today_Sunday)

bool

In [ ]:
cost_of_ice_bag = 12.25
is_ice_bag_expensive = cost_of_ice_bag1 > 10


In [ ]:
is_ice_bag_expensive

True

In [ ]:
is_ice_bag_expensive = cost_of_ice_bag >=13


In [ ]:
is_ice_bag_expensive

False

In [ ]:
type(is_ice_bag_expensive)

bool

In [ ]:
#Booleans are automatically converted to ints when used in arithmetic operations. True is converted to 1 and False is converted to 0.



In [ ]:
5.0+False

5.0

In [ ]:
5+True

6

In [ ]:
# Any value in Python can be converted to a Boolean using the bool function.

# Only the following values evaluate to False (they are often called falsy values):

# The value False itself
# The integer 0
# The float 0.0
# The empty value None
# The empty text ""
# The empty list []
# The empty tuple ()
# The empty dictionary {}
# The empty set set()
# The empty range range(0)
# Everything else evaluates to True (a value that evaluates to True is often called a truthy value).

In [ ]:
bool(False)


False

In [ ]:
bool(0)

False

In [ ]:
bool(True), bool(1), bool(2.0), bool("hello"), bool([1,2]), bool((2,3)), bool(range(10))

(True, True, True, True, True, True, True)

In [ ]:
bool(False),bool(0),bool(0.0),bool(None),bool(""),bool([]),bool({}),bool(range(0))


(False, False, False, False, False, False, False, False)

###None

In [ ]:
nothing = None

In [ ]:
type(nothing)


NoneType

###String

In [ ]:
today = "Saturday"
type(today)

str

In [ ]:
another_pun = "The first time I got a universal remote control, I thought to myself \"This changes everything\"."
another_pun


'The first time I got a universal remote control, I thought to myself "This changes everything".'

In [ ]:
yet_another_pun = '''Son: "Dad, can you tell me what a solar eclipse is?" 
Dad: "No sun."'''
yet_another_pun

'Son: "Dad, can you tell me what a solar eclipse is?" \nDad: "No sun."'

In [ ]:
print(yet_another_pun)


Son: "Dad, can you tell me what a solar eclipse is?" 
Dad: "No sun."


In [ ]:
a_music_pun = """
Two windmills are standing in a field and one asks the other, 
"What kind of music do you like?"  

The other says, 
"I'm a big metal fan."
"""

In [ ]:
a_music_pun

'\nTwo windmills are standing in a field and one asks the other, \n"What kind of music do you like?"  \n\nThe other says, \n"I\'m a big metal fan."\n'

In [ ]:
print(a_music_pun)



Two windmills are standing in a field and one asks the other, 
"What kind of music do you like?"  

The other says, 
"I'm a big metal fan."



In [ ]:
print(a_music_pun)
len(a_music_pun)



Two windmills are standing in a field and one asks the other, 
"What kind of music do you like?"  

The other says, 
"I'm a big metal fan."



141

In [ ]:
multiline_string = """a
b"""
multiline_string


'a\nb'

In [ ]:
len(multiline_string)


3

In [ ]:
#A string can be converted into a list of characters using list function.

list(multiline_string)


['a', '\n', 'b']

In [ ]:
today = "Saturday"
today[0]

'S'

In [ ]:
len(today)

8

In [ ]:
# You can access a part of a string using by providing a start:end range instead of a single index in [].

today[5:8]


'day'

In [ ]:
# You can also check whether a string contains a some text using the in operator.

'day' in today


True

In [ ]:
'xyz' in today

False

In [ ]:
full_name = "Derek O'Brien"
greeting = "Hello"


In [ ]:
full_name + greeting

"Derek O'BrienHello"

In [ ]:
full_name + "   " +greeting +"!"

"Derek O'Brien   Hello!"

In [ ]:
today.lower()

'saturday'

In [ ]:
"saturday".upper()


'SATURDAY'

In [ ]:
"oyehoye".capitalize()

'Oyehoye'

In [ ]:
another_day = today.replace("Satur", "Wednes")


In [ ]:
another_day

'Wednesday'

In [ ]:
today

'Saturday'

In [ ]:
#The .split method splits a string into a list of strings at every occurrence of provided character(s).
"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(",")



['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

In [2]:
#The .strip method removes whitespace characters from the beginning and end of a string.

a_long_line = "       This is a long line with some space before, after,     and some space in the middle..    "
a_long_line

'       This is a long line with some space before, after,     and some space in the middle..    '

In [3]:
a_long_line_stripped = a_long_line.strip()
a_long_line_stripped

'This is a long line with some space before, after,     and some space in the middle..'

In [4]:
len(a_long_line_stripped)



85

##List

In [5]:
fruits = ['apple','banana','cherry']

In [6]:
fruits

['apple', 'banana', 'cherry']

In [7]:
a_list = ['23','hello',None,3.14,fruits,3<=5]
a_list

['23', 'hello', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [8]:
empty_list = []
empty_list

[]

In [9]:
len(fruits)

3

In [10]:
a_list[2:5]

[None, 3.14, ['apple', 'banana', 'cherry']]

In [11]:
a_list[2:10]

[None, 3.14, ['apple', 'banana', 'cherry'], True]

In [13]:
a_list[1:]

['hello', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [14]:
a_list[:]

['23', 'hello', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [15]:
a_list

['23', 'hello', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [22]:
a_list[:len(a_list)]

['23', 'hello', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [18]:
len(a_list)

6

In [23]:
a_list[-2:-5]

[]

In [24]:
a_list[-5:-2]

['hello', None, 3.14]

In [25]:
a_list[1]='Hi'
a_list

['23', 'Hi', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [26]:
# append to add at end 
a_list.append('Mango')
a_list

['23', 'Hi', None, 3.14, ['apple', 'banana', 'cherry'], True, 'Mango']

In [27]:
a_list.insert(2,'hola')
a_list

['23', 'Hi', 'hola', None, 3.14, ['apple', 'banana', 'cherry'], True, 'Mango']

### .remove()   by value
    
    .pop()   by index

In [30]:
a_list.remove('Hi')
a_list

['23', 'hola', None, 3.14, ['apple', 'banana', 'cherry'], True, 'Mango']

In [31]:
fruits.pop(1)
fruits

['apple', 'cherry']

In [34]:
# in operator
"pineple" in fruits


False

In [35]:
"apple" in fruits

True

### concatination   (+) operator

In [36]:
fruits

['apple', 'cherry']

In [37]:
more_fruits = fruits + ['apple','grapes','guava']
more_fruits

['apple', 'cherry', 'apple', 'grapes', 'guava']

In [38]:
more_fruits.insert(2,["orange","kiwi"])
more_fruits

['apple', 'cherry', ['orange', 'kiwi'], 'apple', 'grapes', 'guava']

In [42]:
# reverse the order of elements in a list 
fruits[::-1]

['cherry', 'apple']

In [43]:
# add elements of one list to the the end of another list   .extend()
list1 = ["A","B"]
list2 = ["C","D"]
list1.extend(list2)


In [44]:
list1

['A', 'B', 'C', 'D']

In [45]:
#reverse  .reverse()

['C', 'D']

In [46]:
list1.reverse()

In [47]:
list1

['D', 'C', 'B', 'A']

In [48]:
list1.sort()
list1

['A', 'B', 'C', 'D']

In [55]:
list1.count("A")


1

In [59]:
points = [1,"AB","ABC",4, 2, 9, 7, 8, 9, 3, 1]

x = points.count("AB")

In [60]:
x

1

In [64]:
person = dict(Name = "Mansi",Surname = "Patel",sex="Female",age=30,married="True")
person

{'Name': 'Mansi',
 'Surname': 'Patel',
 'age': 30,
 'married': 'True',
 'sex': 'Female'}

In [65]:
type(person)

dict

In [ ]:
# access values using key


## Control statments ---- if-else



In [1]:
a_number = 34
if a_number %2==0:
  print("we are inside a if block")
  print(f"The given number {a_number} is even")


we are inside a if block
The given number 34 is even


In [4]:
today = "Sunday"
if today == "Monday":
  print("Today is monday")
elif today == "Tuesday":
  print("Today is tuesday")
elif today == "Wednesday":
  print("Today is wednesday")
elif today == "Sunday":
  print("Today is day of Sun sunday")

Today is day of Sun sunday


In [10]:
a_number = 30
if a_number % 3 ==0 and a_number % 5 ==0:
  print(f"The number {a_number} is divisable by 3 and 5")
elif not a_number % 5 == 0:
  print(f"the number {a_number} is not divisable by 5 ")


The number 30 is divisable by 3 and 5


In [11]:
# non-boolean condition
# 0,"",{},[] 
# it means falsy values evaluate to false and others as True



In [14]:
if "":
  print("the condition is evaluated to True")
else:
  print("the condition is evaluated to false")


the condition is evaluated to false


In [18]:
if None:
  print("The condition evaluated to True")
else:
  print("The condition is False")

The condition is False


In [28]:
# while loop

# factorial of number

%%time
result = 1
i = 1

while i <= 100:
  result = result * i
  print(f"i {i} th result is {result}")
  i = i+1

print(f"the factorial of 10 is {result}")

i 1 th result is 1
i 2 th result is 2
i 3 th result is 6
i 4 th result is 24
i 5 th result is 120
i 6 th result is 720
i 7 th result is 5040
i 8 th result is 40320
i 9 th result is 362880
i 10 th result is 3628800
i 11 th result is 39916800
i 12 th result is 479001600
i 13 th result is 6227020800
i 14 th result is 87178291200
i 15 th result is 1307674368000
i 16 th result is 20922789888000
i 17 th result is 355687428096000
i 18 th result is 6402373705728000
i 19 th result is 121645100408832000
i 20 th result is 2432902008176640000
i 21 th result is 51090942171709440000
i 22 th result is 1124000727777607680000
i 23 th result is 25852016738884976640000
i 24 th result is 620448401733239439360000
i 25 th result is 15511210043330985984000000
i 26 th result is 403291461126605635584000000
i 27 th result is 10888869450418352160768000000
i 28 th result is 304888344611713860501504000000
i 29 th result is 8841761993739701954543616000000
i 30 th result is 265252859812191058636308480000000
i 31 th 

In [9]:
# "while" loops

line = "*"
max_length = 10

while len(line) <= max_length:
  print(line)
  line += "*"

while len(line) >0:
  print(line)
  line= line[:len(line)-1]

*
**
***
****
*****
******
*******
********
*********
**********
***********
**********
*********
********
*******
******
*****
****
***
**
*


### for loop

In [1]:
# 
days = ['Monday','Tueday',None,'Wednesday']

for i in days:
  print(i)

Monday
Tueday
None
Wednesday


In [2]:
# looping over string

for char in 'Monday':
  print(char)

M
o
n
d
a
y


In [5]:
# looping over List

for fruit in ['Apple','Banana','Guava']:
  print(f"fruit name is :{fruit}")



fruit name is :Apple
fruit name is :Banana
fruit name is :Guava


In [8]:
# looping over dictionary

person = {
    'name':'Mansi Patel',
    'Sex':'Female',
    'married':'Yes'
}

for key in person:
  print(f"Key:{key} and value: {person[key]}")

Key:name and value: Mansi Patel
Key:Sex and value: Female
Key:married and value: Yes


In [10]:
for value in person.values():
  print(value)

Mansi Patel
Female
Yes


In [11]:
for key in person.keys():
  print(key)

name
Sex
married


In [12]:
for key_values in person.items():
  print(key_values)

('name', 'Mansi Patel')
('Sex', 'Female')
('married', 'Yes')


In [13]:
# range 
for i in range(7):
  print(i)

0
1
2
3
4
5
6


In [14]:
for i in range(3,10):
  print(i)

3
4
5
6
7
8
9


In [15]:
for i in range(1,7,3):
  print(i)

1
4


In [4]:
# ranges are used to iterate over list

l1 = ['Monday','tuesday','wednesday']

for i in range(len(l1)):
  print(f"value at {i} th position is {l1[i]}")


value at 0 th position is Monday
value at 1 th position is tuesday
value at 2 th position is wednesday


In [5]:
#enumarate

for i in enumerate(l1):
  print(i)

(0, 'Monday')
(1, 'tuesday')
(2, 'wednesday')


In [8]:
# break , pass , continue
weekdays = ["Monday","Tuesday","Wednesday","Thursday","Friday"]

for day in weekdays:
  print(f"today is {day}")
  if (day=="Wednesday"):
    break

today is Monday
today is Tuesday
today is Wednesday


In [11]:
weekdays = ["Monday","Tuesday","Wednesday","Thursday","Friday"]

for day in weekdays:
  if day == "Wednesday":
    print("I dont work on wednesday!")
    continue
  print(f"Today is {day}")

Today is Monday
Today is Tuesday
I dont work on wednesday!
Today is Thursday
Today is Friday


In [12]:
for days in weekdays:
  pass

### Nested for and while loop

##Functions

In [13]:
def say_hello():
  print("Hello there")
  print("How r u")

In [14]:
say_hello()

Hello there
How r u


In [15]:
print(say_hello())

Hello there
How r u
None


In [16]:
# function Arguments

def say_hello(name):
  print(f"My name is {name}")


In [18]:
say_hello("Mansi")

My name is Mansi


In [19]:
def filter_even(num_list):
  result_list = []
  for number in num_list:
    if number % 2 ==0:
      result_list.append(number)
  return result_list 

In [20]:
filter_even([1,2,3,4,5,6,7])

[2, 4, 6]

In [2]:
# writing great function in python
# counting loan amount using python

house_cost = 1,260,000
down_payment = 300000
interest_rate= 0.10
year = 8




In [3]:
# 1.simplest function without any parameters 

def loan_emi(amount):
  emi = amount/12
  print(f"The EMI is {emi}")
  

In [4]:
loan_emi(1260000)

The EMI is 105000.0


In [5]:
#Local variables and scope
 # duration of the loan , in months

def loan_emi(amount,duration):
  emi = amount/duration
  print(f"The EMI is {emi} ")

In [8]:
loan_emi(1260000,10*12)

The EMI is 10500.0 


In [9]:
loan_emi(1260000,8*12)

The EMI is 13125.0 


In [10]:
#with return values
def loan_emi(amount,duration):
  emi = amount/duration
  return emi

In [13]:
emi1 = loan_emi(1260000,8*12)

In [12]:
emi2 = loan_emi(1260000,10*12)


In [14]:
emi1,emi2

(13125.0, 10500.0)

In [15]:
emi1-emi2


2625.0

In [16]:
# including loan_amount
def loan_emi(amount,duration,down_payment=0):
  loan_amount = amount - down_payment
  emi = loan_amount/duration
  return emi

In [19]:
emi1 = loan_emi(1260000,10*12,300000)
emi1

8000.0

In [20]:
emi2 = loan_emi(1260000,8*12,300000)
emi2

10000.0

In [21]:
# add intrest calculate
#*****************   EMI = P × r × (1 + r)n/((1 + r)n - 1) where P= Loan amount, r= interest rate, n=tenure in number of months

def loan_emi(amount,interest_rate,duration,down_payment=0):
  loan_amount =  amount- down_payment
  emi = loan_amount*interest_rate*((1+interest_rate)**duration) /((1+interest_rate)**duration-1)
  return emi

In [23]:
# option 1 --- 8 months and 0.10 interest
emi1 = loan_emi(1260000,0.10/12,8*12,300000)

14567.19753389219

In [30]:
# option 2
emi2 = loan_emi(1260000,0.08/12,10*12,300000)
emi2



11647.449058114344

In [31]:
# Modules and Library

import math


In [33]:
math.ceil(2.222)

3

In [ ]:
# exception -------------try -catch





In [2]:
# function practice

kanto = [12,34,55]
johto = [91,88,64]
hoenn = [102,43,37]
sinnoh = [69,96,70]

w1,w2,w3 = 0.3,0.5,0.7

weights = [w1,w2,w3]

In [3]:
def crop_yield(region,weights):
  result = 0
  for x,w in zip(region,weights):
    result = result + x*w
  return result

In [7]:
crop_yield(johto,weights)

116.1

# Numpy

In [ ]:
# to install numpy package
#! pip install numpy --upgrade --quiet

In [2]:
import numpy as np 


In [10]:
kanto = np.array([12,34,55])
weights = np.array([w1,w2,w3])



In [17]:
np.dot(kanto ,weights).sum()

59.1

In [14]:
kanto * weights

array([ 3.6, 17. , 38.5])

In [27]:
#python list
arra1 = list(range(30))
arra2 = list(range(10,40))

In [28]:
# Numpy Arrays
arr1_np = np.array(arra1)
arr2_np = np.array(arra2)

In [33]:
%%time
result = 0
for x1,x2 in zip(arra1,arra2):
  result = result + x1*x2
result 

CPU times: user 20 µs, sys: 2 µs, total: 22 µs
Wall time: 25.7 µs


In [30]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: user 1.12 ms, sys: 0 ns, total: 1.12 ms
Wall time: 1.36 ms


12905

In [35]:
# 2D array
climate_data = np.array([[10,20,30],
                        [11,22,33],
                        [44,55,66]])
climate_data

array([[10, 20, 30],
       [11, 22, 33],
       [44, 55, 66]])

In [36]:
climate_data.dtype

dtype('int64')

In [42]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr4 = np.array([1,1,1])



In [43]:
arr3+arr4

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.rand(5)

array([0.95322241, 0.31191876, 0.5235662 , 0.89968652, 0.03740709])

In [6]:
np.random.randn(5)

array([-0.49281271, -0.01822703, -0.78717505, -0.38921617,  0.46246078])

In [10]:
np.arange(10,90)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [9]:
np.linspace(3,27)

array([ 3.        ,  3.48979592,  3.97959184,  4.46938776,  4.95918367,
        5.44897959,  5.93877551,  6.42857143,  6.91836735,  7.40816327,
        7.89795918,  8.3877551 ,  8.87755102,  9.36734694,  9.85714286,
       10.34693878, 10.83673469, 11.32653061, 11.81632653, 12.30612245,
       12.79591837, 13.28571429, 13.7755102 , 14.26530612, 14.75510204,
       15.24489796, 15.73469388, 16.2244898 , 16.71428571, 17.20408163,
       17.69387755, 18.18367347, 18.67346939, 19.16326531, 19.65306122,
       20.14285714, 20.63265306, 21.12244898, 21.6122449 , 22.10204082,
       22.59183673, 23.08163265, 23.57142857, 24.06122449, 24.55102041,
       25.04081633, 25.53061224, 26.02040816, 26.51020408, 27.        ])

In [11]:
#
import os

In [12]:
os.getcwd()

'/content'

In [13]:
help(os.listdir)

Help on built-in function listdir in module posix:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [14]:
os.listdir(".")

['.config', 'sample_data']

# File operations

In [33]:
#_____________________

file1 = open("sample3.txt",mode="r",encoding='UTF-8')
file1

<_io.TextIOWrapper name='sample3.txt' mode='r' encoding='UTF-8'>